security:
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_manager

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_TEACHER: AUTHENTICATED
        ROLE_STUDENT: AUTHENTICATED
        ROLE_ADMIN:   {ROLE_STUDENT, ROLE_TEACHER}
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

