security:
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    role_hierarchy:
        ROLE_ADMIN: [ROLE_STUDENT, ROLE_TEACHER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
